fullnameOverride: "connector-slack"

image:
  repository: oc/connector-slack
  tag: "latest"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8082

# secretRef: connector-slack-secrets

env:
  CONNECTOR_SLACK_ADDR: ":8082"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
