fullnameOverride: "connector-slack"

image:
  repository: aag/connector-slack
  tag: "1.0"
  pullPolicy: IfNotPresent

replicas: 1

service:
  port: 8082

env:
  CONNECTOR_SLACK_ADDR: ":8082"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
