apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aag-connector-slack.fullname" . }}
  labels:
    {{- include "aag-connector-slack.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aag-connector-slack.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from gateway only
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: aag-gateway
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
